baseURL = 'https://blog.asafut.com/'
languageCode = 'es-la'
title = "tavocg"

theme = 'theme'
defaultContentLanguage = 'es'

[caches]
[caches.images]
dir = ':cacheDir/images'

[module]
[module.hugoVersion]
extended = false
min = '0.146.0'
